<Project>
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>false</IsPackable>
		<AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>

		<SignAssembly>true</SignAssembly>
		<AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)OrchardCoreContrib.PoExtractor.snk</AssemblyOriginatorKeyFile>
	</PropertyGroup>
</Project>
